#ifndef R4R_RECONSTRUCTION_GLOBAL_H
#define R4R_RECONSTRUCTION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(R4R_RECONSTRUCTION_LIBRARY)
#  define R4R_RECONSTRUCTIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define R4R_RECONSTRUCTIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // R4R_RECONSTRUCTION_GLOBAL_H
